version: "3"
services:
  db:
    build: ..
    container_name: my_postgresql
    ports:
      - "${POSTGRES_DOCKER_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      TZ: "Asia/Tokyo"
    env_file:
      - ./.env
    volumes:
      - ./db/data:/var/lib/postgresql/data